### ISSUE TITLE
兄弟 我这里怎么运行不成功

### ISSUE THREAD

**Issue by Dancarol** [TorCroft/gatepasscode#1]
[Invalid workflow file: .github/workflows/main.yml#L32]
The workflow is not valid. .github/workflows/main.yml (Line: 32, Col: 20): Unexpected symbol: '&密码'. Located at position 31 within expression: secrets.UID_PWD账号&密码.github/workflows/main.yml (Line: 37, Col: 14): Unexpected symbol: 'EMAIL867358948@qq'. Located at position 9 within expression: secrets.EMAIL867358948@qq.com

**Comment by TorCroft** [comment]
`.github/workflows/` 下的两个yml文件不需要修改的，Fork后创建`UID_PWD`,`EMAIL`,`USERNAME`三个secret变量就行了

**Comment by Dancarol** [comment]
您的来信我已收到，谢谢。
